AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'Gemfile'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
